/// <reference types="Cypress" />

describe('Exclusão de beneficiário', function () {
    this.beforeEach(function () {
        cy.loginEmpresa()
        //cy.get('.sc-dkIXFM > :nth-child(1) > .MuiButtonBase-root-321').should('be.visible').click()
    })

    it('Campo telefone é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeClickComand()
        cy.get(':nth-child(6) > .MuiFormControl-root-679 > .MuiFormHelperText-root-745')
            .should('have.text', 'O telefone é obrigatório')
    })
    it('Campo e-mail é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeClickComand()
        cy.get(':nth-child(7) > .MuiFormControl-root-679 > .MuiFormHelperText-root-745')
            .should('have.text', 'O e-mail é obrigatório')
    })
    it('Campo Anexar documento é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeClickComand()
        cy.get('[style="color: rgb(244, 67, 54); font-size: 0.75rem; margin: 5px;"]')
            .should('have.text', 'O anexo da solicitação do beneficiário é obrigatório')
    })
    it('Dados da empresa são exibidos, Nome da empresa', function () {
        cy.excludeAccess()
        cy.get(':nth-child(2) > :nth-child(2) > .MuiTypography-root-409')
            .should('have.value', '')
    })
    it('Dados do beneficiário do plano são exibidos', function () {
        cy.excludeAccess()
        cy.get(':nth-child(2) > :nth-child(2) > .MuiTypography-root-409')
            .should('have.value', '')
    })
    it('Campo motivo da exclusão é obrigatporio', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.get('label[for="fileUpload"]')
            .should('not.have.value')
            .selectFile('./cypress/fixtures/Logo Bossabox.png')
        cy.excludeClickComand()
        cy.get('.MuiAlert-message > div')
            .should('be.visible')
    })
    it('Campo data de exclusão preenchido por default', function () {
        cy.excludeAccess()
        cy.get('.MuiGrid-grid-xs-4-600 > .MuiFormControl-root-679 > .MuiInputBase-root-687 > .MuiInputBase-input-695')
            .should('be.visible')
    })
    it('Campo O beneficiário contribuiu com o pagamento parcial ou integral da mensalidade do plano? é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.get('#5').click()
        cy.get('#mui-component-select-reason').click()
        cy.get('.MuiList-root-393 > [tabindex="0"] > :nth-child(1)').click()
        cy.excludeClickComand()

    })
    it('Campo O fim da relação empregatícia ou estatutária deu-se por: é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.get('#5').click()
        cy.get('#mui-component-select-reason').click()
        cy.get('.MuiList-root-393 > [tabindex="0"] > :nth-child(1)').click()
        cy.get('#sim').click()
        cy.excludeClickComand()
        cy.get(':nth-child(8) > :nth-child(3) > span')
            .should('have.text', 'O motivo de desligamento é obrigatório')
    })

    it('Campo O beneficiário foi cientificado sobre seu direito de solicitar plano ex empregado? é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.get('#5').click()
        cy.get('#mui-component-select-reason').click()
        cy.get('.MuiList-root-393 > [tabindex="0"] > :nth-child(1)').click()
        cy.get('#sim').click()
        cy.excludeClickComand()
        cy.get(':nth-child(8) > :nth-child(4) > span')
            .should('have.text', 'Campo obrigatório')
    })
    it('Campo Anexar Termo de Ciência do Plano Ex Empregado é obrigatório é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.get('#5').click()
        cy.get('#mui-component-select-reason').click()
        cy.get('.MuiList-root-393 > [tabindex="0"] > :nth-child(1)').click()
        cy.get('#sim').click()
        cy.excludeClickComand()
        cy.get(':nth-child(5) > [style="color: rgb(244, 67, 54); font-size: 0.75rem; margin: 5px;"]')
            .should('have.text', 'O anexo do Termo de Ciência do Beneficiário é obrigatório')
    })
    it('O campo Data de Ciência do plano Ex empregado é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.get('#5').click()
        cy.get('#mui-component-select-reason').click()
        cy.get('.MuiList-root-393 > [tabindex="0"] > :nth-child(1)').click()
        cy.get('#sim').click()
        cy.excludeClickComand()
        cy.get(':nth-child(6) > .MuiFormControl-root-679 > .MuiFormHelperText-root-745')
            .should('have.text', 'Campo obrigatório')
    })
    it('O campo O beneficiário optou pela manutenção do plano na condição de ex-empregado? é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.get('#5').click()
        cy.get('#mui-component-select-reason').click()
        cy.get('.MuiList-root-393 > [tabindex="0"] > :nth-child(1)').click()
        cy.get('#sim').click()
        cy.excludeClickComand()
        cy.get(':nth-child(7) > span')
            .should('have.text', 'Campo obrigatório')
    })
    it.skip('O campo Por quantos meses o beneficiário titular contribuiu com o pagamento da mensalidade? é obrigatório', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.excludeByCompany()
        cy.excludeClickComand()
        //cy.get(':nth-child(2) > .MuiFormControl-root-679 > .MuiFormHelperText-root-745')
        //.should('have.text','Campo deve ser preencido')
    })
    it('Exclusão de titular solicitação da Empresa', function () {
        cy.excludeAccess()
        cy.excludeBeneficiaryData()
        cy.excludeByCompany()
        cy.excludeClickComand()
        cy.logout()
        cy.loginAdmin()
        cy.approveExclude()
    })   
    it('Exclusão de titular solicitação do beneficiário', function () {
        cy.excludeBeneficiary()
        cy.logout()
        cy.loginAdmin()
        cy.approveExclude()
    })

})